Description: A VPC Cloudformation template containing EC2, Pubic/Private Subnets, Internet Gateway and Security Groups

Parameters:
  FridayHITTVPCCIDR:
    Description: IP range associated with the VPC for the FridayHITT company
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetCIDR:
    Description: IP range for the Public Subnet
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnetCIDR:
    Description: IP range for the Private Subnet
    Type: String
    Default: 10.0.2.0/24

  AvailabilityZone:
    Description: Availability Zone for the subnets
    Type: AWS::EC2::AvailabilityZone::Name
    ConstraintDescription: Specify an available Availability Zone

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium

  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

Mappings:
  RegionMap:
    eu-west-1:
      AMI: ami-00385a401487aefa4
    eu-west-2:
      AMI: ami-0acc77abdfc7ed5a6
    eu-west-3:
      AMI: ami-00d81861317c2cc1f
    eu-central-1:
      AMI: ami-08ec94f928cf25a9d  
    eu-north-1:
      AMI: ami-02db68a01488594c5      

Resources:
  # VPC block
  FridayHITTVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref FridayHITTVPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: FridayHITT-vpc

  # Internet Gateway block
  FridayHITTVPCInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: FridayHITT-IGW

  AttachFridayHITTVPCInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FridayHITTVPC
      InternetGatewayId: !Ref FridayHITTVPCInternetGateway 

  # Public Subnet block
  FridayHITTVPCPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FridayHITTVPC
      CidrBlock: !Ref PublicSubnetCIDR
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: FridayHITT-vpc-Public-Subnet

  # Private Subnet block
  FridayHITTVPCPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FridayHITTVPC
      CidrBlock: !Ref PrivateSubnetCIDR
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: FridayHITT-vpc-Private-Subnet

  # Security Groups
  FridayHITTJumpBoxEC2PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref FridayHITTVPC
      GroupDescription: "Public Security Group allowing only SSH"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0        

  FridayHITTPublicEC2PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref FridayHITTVPC
      GroupDescription: "Public Security Group allowing SSH, HTTP, and HTTPS"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref FridayHITTJumpBoxEC2PublicSecurityGroup
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0      

  FridayHITTPrivateEC2PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref FridayHITTVPC
      GroupDescription: "Private Security Group allowing only SSH from JumpBox"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref FridayHITTJumpBoxEC2PublicSecurityGroup

  # Route Tables
  FridayHITTPublicEC2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FridayHITTVPC
      Tags:
        - Key: Name
          Value: FridayHITT-publicroutetable

  FridayHITTDefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachFridayHITTVPCInternetGateway
    Properties:
      RouteTableId: !Ref FridayHITTPublicEC2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FridayHITTVPCInternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref FridayHITTPublicEC2RouteTable
      SubnetId: !Ref FridayHITTVPCPublicSubnet

  FridayHITTPrivateEC2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FridayHITTVPC

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref FridayHITTPrivateEC2RouteTable
      SubnetId: !Ref FridayHITTVPCPrivateSubnet    

  # EC2 Instances
  FridayHITTJumpBoxEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      SubnetId: !Ref FridayHITTVPCPublicSubnet
      SecurityGroupIds: 
        - !Ref FridayHITTJumpBoxEC2PublicSecurityGroup
      Tags:
        - Key: Name
          Value: FridayHITT-JumpBox

  FridayHITTPublicInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      SubnetId: !Ref FridayHITTVPCPublicSubnet
      SecurityGroupIds: 
        - !Ref FridayHITTPublicEC2PublicSecurityGroup
      Tags:
        - Key: Name
          Value: FridayHITT-PublicInstance

  FridayHITTPrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      SubnetId: !Ref FridayHITTVPCPrivateSubnet
      SecurityGroupIds: 
        - !Ref FridayHITTPrivateEC2PrivateSecurityGroup
      Tags:
        - Key: Name
          Value: FridayHITT-PrivateInstance
