Description: A VPC Cloudformation template containing EC2, Pubic/Private Subnets, Gateway and Security Groups

Resources:
  #VPC block
  FridayHITTVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: FridayHITT-vpc

  #Public EC2 Instance block
  FridayHITTPublicInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: FridayHITT_Sriram-1
      ImageId: ami-00385a401487aefa4

  #Private EC2 Instance block
  FridayHITTPrivateInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: FridayHITT_Sriram-1
      ImageId: ami-00385a401487aefa4    


